### ISSUE TITLE
__contains__ pollutes __dict__ with empty Namespace values

### ISSUE THREAD

**Issue by christian-storm** [shakefu/pytool#14]
```python
from pytool.lang import Namespace
f = Namespace({'a': {'a1': [1]}, 'b': {'b1': [2]}, 'c': {'d': [1, 2, 3]}})
print(bool('e' in f))  # False but creates f.e = Namespace()
print(bool('e' in f.__dict__))  # True
```

Doesn't it make sense that 'e' would only be added in assignment and not in attribute lookup/contains?

The reason I found this was because I added a method knitems
```python
    for name, value in self.__dict__.items():
            yield name, value
```
to be able to iterate one level at a time.  I've had to add
```python
        if isinstance(value, Namespace) and bool(value):
```
in order to make it work.

**Comment by shakefu** [comment]
Good find. I'll see if I can get a patch fix published this week unless you want to PR earlier.

**Comment by christian-storm** [comment]
I'm a bit flat out right now.  I may be able to get to it in a week or so.

**Comment by christian-storm** [comment]
This seems to have fixed things for me but wanted your opinion on whether this is the right fix or not.
Basically, if the contains is going to return False just delete the empty vestigial namespace created by __getattr__. 

What do you think?
```python
    def __contains__(self, name):
        names = name.split('.')

        obj = self
        for name in names:
            obj = getattr(obj, name)

        if isinstance(obj, Namespace):
            if obj.__dict__:
                return True
            else:
                del self.__dict__[name]  # <--- I added this line
                return False
        else:
            return True
```

**Comment by shakefu** [comment]
@christian-storm This is fixed in master. Apologies for the long delay, GitHub notifications suck.
